name: Deploy AWS Infrastructure with Terraform

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest  # Set the environment for the workflow

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.6.0'  # Specify the Terraform version you want to use

      # Step 3: Configure AWS Credentials using OIDC
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::120569613442:role/amit_ec2_s3_cloudfront  # Your IAM role ARN
          aws-region: us-east-1  # Specify AWS region

      # Step 4: Initialize Terraform (downloads required plugins)
      - name: Terraform Init
        run: terraform init

      # Step 5: Run Terraform Plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      # Step 6: Apply the Terraform Plan (approve automatically)
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
