name: Deploy AWS Infrastructure with Terraform

# Trigger the workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest  # Set the environment for the workflow

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.6.0'  # Specify the Terraform version you want to use

    # Step 3: Configure AWS Credentials using OIDC (AWS Identity Federation)
    - name: Configure AWS Credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role_to_assume: arn:aws:iam::YOUR_ACCOUNT_ID:role/YOUR_OIDC_ROLE_NAME
        aws_region: us-east-1

    # Step 4: Initialize Terraform (downloads required plugins)
    - name: Terraform Init
      run: terraform init

    # Step 5: Run Terraform Plan
    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan

    # Step 6: Apply the Terraform Plan (approve automatically)
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
